version: "3.1"

services:
  db:
    image: mysql
    container_name: mysql_service
    command: --default-authentication-plugin=mysql_native_password
    ports: 
      - 3309:3306
    volumes:
      - /home/data/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: senha